services:

  scraper:
    restart: always
    image: ghcr.io/osu-justicetech/case_collector:main
    volumes:
      - db:/app/db
    command: ["sh","-c","uv run manage.py collectstatic --noinput && uv run manage.py migrate && uv run uvicorn eviction_tool.asgi:application --host 0.0.0.0"]
    environment:
      DJANGO_TRUSTED_ORIGINS: "http://localhost:8001"
      DJANGO_ALLOWED_HOSTS: "localhost"
    ports:
      - "0.0.0.0:8000:8000"


volumes:
  db:
