# Generated by Django 6.0.3 on 2026-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtcase",
            name="case_number",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
