# Generated by Django 6.0.3 on 2026-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_courtcase_case_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposition",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
