# Generated by Django 6.0.3 on 2026-05-08 15:53

from django.db import migrations

CREATE_SQL = """
CREATE VIEW IF NOT EXISTS latest_overview AS
SELECT
    c.case_number,
    c.source_id,
    s.created_at,
    docket_dates.earliest_date AS earliest_docket,
    docket_dates.latest_date AS latest_docket,
    disp.code,
    disp.judge,
    disp.status,
    disp.status_date,
    disp.date,
    disp_counts.*,
    party_counts.*,
    first_defendant.name AS stdef_name,
    first_defendant.address AS stdef_address,
    first_defendant.city AS stdef_city,
    first_defendant.state AS stdef_state,
    first_defendant.zip_code AS stdef_zip_code,
    
    first_plaintiff.name AS stptf_name,
    first_plaintiff.address AS stptf_address,
    first_plaintiff.city AS stptf_city,
    first_plaintiff.state AS stptf_state,
    first_plaintiff.zip_code AS stptf_zip_code,
    
    plaintiff_primary_attorney.name AS stptfatt_name,
    plaintiff_primary_attorney.address AS stptfatt_address,
    plaintiff_primary_attorney.city AS stptfatt_city,
    plaintiff_primary_attorney.state AS stptfatt_state,
    plaintiff_primary_attorney.zip_code AS stptfatt_zip_code
FROM cases_courtcase c

JOIN cases_casesnapshot s
    ON s.case_id = c.id

-- get latest snapshot
JOIN (
    SELECT case_id, MAX(created_at) AS max_created_at
    FROM cases_casesnapshot
    GROUP BY case_id
) latest
    ON latest.case_id = s.case_id
   AND latest.max_created_at = s.created_at

-- Start and End of Docket entries
LEFT JOIN (
    SELECT
        snapshot_id,
        MIN(date) AS earliest_date,
        MAX(date) AS latest_date
    FROM cases_docketentry
    GROUP BY snapshot_id
) docket_dates
    ON docket_dates.snapshot_id = s.id

-- Get latest disposition, or any one with NULL date
LEFT JOIN (
    SELECT *
    FROM (
        SELECT
            d.*,
            ROW_NUMBER() OVER (
                PARTITION BY d.snapshot_id
                ORDER BY
                    CASE WHEN d.date IS NULL THEN 1 ELSE 0 END,
                    d.date DESC
            ) AS rn
        FROM cases_disposition d
    ) ranked
    WHERE rn = 1
) disp
    ON disp.snapshot_id = s.id

-- Number of Dispositions
LEFT JOIN (
    SELECT
        snapshot_id,
        COUNT(*) AS disposition_count
    FROM cases_disposition
    GROUP BY snapshot_id
) disp_counts
    ON disp_counts.snapshot_id = s.id

-- Number of Parties per Side
LEFT JOIN (
    SELECT
        snapshot_id,
        SUM(CASE
            WHEN side = 'DEFENDANT' AND role = '' THEN 1
            ELSE 0
        END) AS defendant_count,
        SUM(CASE
            WHEN side = 'PLAINTIFF' AND role = '' THEN 1
            ELSE 0
        END) AS plaintiff_count
    FROM cases_party
    GROUP BY snapshot_id
) party_counts
    ON party_counts.snapshot_id = s.id

-- First DEFENDANT
LEFT JOIN (
    SELECT *
    FROM (
        SELECT
            p.*,
            ROW_NUMBER() OVER (
                PARTITION BY p.snapshot_id
                ORDER BY p.id
            ) AS rn
        FROM cases_party p
        WHERE p.role = ''
          AND p.side = 'DEFENDANT'
    ) ranked
    WHERE rn = 1
) first_defendant
    ON first_defendant.snapshot_id = s.id

-- First PLAINTIFF
LEFT JOIN (
    SELECT *
    FROM (
        SELECT
            p.*,
            ROW_NUMBER() OVER (
                PARTITION BY p.snapshot_id
                ORDER BY p.id
            ) AS rn
        FROM cases_party p
        WHERE p.role = ''
          AND p.side = 'PLAINTIFF'
    ) ranked
    WHERE rn = 1
) first_plaintiff
    ON first_plaintiff.snapshot_id = s.id

LEFT JOIN (
    SELECT *
    FROM (
        SELECT
            p.*,
            ROW_NUMBER() OVER (
                PARTITION BY p.snapshot_id
                ORDER BY p.id
            ) AS rn
        FROM cases_party p
        WHERE p.side = 'PLAINTIFF'
          AND p.role = 'PRIMARY ATTORNEY'
    ) ranked
    WHERE rn = 1
) plaintiff_primary_attorney
    ON plaintiff_primary_attorney.snapshot_id = s.id
;
"""

DROP_SQL = "DROP VIEW IF EXISTS latest_overview;"


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20260507_1308"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        )
    ]
