# Generated by Django 6.0.3 on 2026-05-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20260508_1553"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disposition",
            options={"ordering": ("date",)},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("start",)},
        ),
    ]
