# Generated by Django 6.0.3 on 2026-05-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_disposition_options_alter_event_options"),
        ("geocode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geocode.location",
            ),
        ),
    ]
