# Generated by Django 6.0.3 on 2026-07-02 19:30

from django.db import migrations

from django.db import connection

CREATE_SQL = f"""
CREATE UNIQUE INDEX latest_overview_uidx ON public.latest_overview (id);
"""

DROP_SQL = "DROP INDEX latest_overview_uidx;"

if connection.vendor in "sqlite":
    CREATE_SQL = ""
    DROP_SQL = ""


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_auto_20260702_1358"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        )
    ]
