# Generated by Django 6.0.3 on 2026-07-17 17:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_auto_20260702_1930"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestOverview",
            fields=[
                ("case_number", models.CharField(editable=False)),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "snapshot",
                    models.OneToOneField(
                        db_column="id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="cases.casesnapshot",
                    ),
                ),
                ("earliest_docket", models.DateField(editable=False)),
                ("latest_docket", models.DateField(editable=False)),
                ("code", models.CharField(editable=False)),
                ("date", models.DateField(editable=False, null=True)),
                ("judge", models.CharField(editable=False)),
                ("status", models.CharField(editable=False)),
                ("status_date", models.DateField(editable=False)),
                ("disposition_count", models.SmallIntegerField(editable=False)),
                ("defendant_count", models.SmallIntegerField(editable=False)),
                ("plaintiff_count", models.SmallIntegerField(editable=False)),
                ("stdef_name", models.CharField(editable=False)),
                ("stdef_address", models.CharField(editable=False)),
                ("stdef_city", models.CharField(editable=False, null=True)),
                ("stdef_state", models.CharField(editable=False, null=True)),
                ("stdef_zip_code", models.CharField(editable=False, null=True)),
                ("full_address", models.CharField(editable=False)),
                ("street_number", models.CharField(blank=True, editable=False)),
                ("street_name", models.CharField(blank=True, editable=False)),
                ("street_type", models.CharField(blank=True, editable=False)),
                ("street_direction", models.CharField(blank=True, editable=False)),
                ("unit_type", models.CharField(blank=True, editable=False)),
                ("unit_number", models.CharField(blank=True, editable=False)),
                ("city", models.CharField(blank=True, editable=False)),
                ("county", models.CharField(blank=True, editable=False)),
                ("state_code", models.CharField(blank=True, editable=False)),
                ("postal_code", models.CharField(blank=True, editable=False)),
                ("country", models.CharField(blank=True, editable=False)),
                (
                    "rooftop",
                    django.contrib.gis.db.models.fields.PointField(
                        editable=False, srid=4326
                    ),
                ),
                (
                    "geocode_score",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "geocode_rank",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                ("geocode_type", models.CharField(blank=True, editable=False)),
                ("stptf_name", models.CharField(editable=False)),
                ("stptf_address", models.CharField(editable=False)),
                ("stptf_city", models.CharField(editable=False, null=True)),
                ("stptf_state", models.CharField(editable=False, null=True)),
                ("stptf_zip_code", models.CharField(editable=False, null=True)),
                ("stptfatt_name", models.CharField(editable=False)),
                ("stptfatt_address", models.CharField(editable=False)),
                ("stptfatt_city", models.CharField(editable=False, null=True)),
                ("stptfatt_state", models.CharField(editable=False, null=True)),
                ("stptfatt_zip_code", models.CharField(editable=False, null=True)),
            ],
            options={
                "db_table": "latest_overview",
                "managed": False,
            },
        ),
    ]
