# Generated by Django 6.0.3 on 2026-07-23 18:56

from django.db import migrations

CREATE_SQL = """
CREATE VIEW daily_events AS
  SELECT
    d.date,

    -- Distinct cases where the earliest docket entry was filed on this day
    COUNT(DISTINCT s.id) FILTER (
        WHERE s.earliest_date = d.date
    ) AS cases_filed,

    -- Writs issued on this day
    COUNT(*) FILTER (
        WHERE d.text IN (
            'WRIT OF RESTITUTION ISSUED',
            'WRIT OF RESTITUTION AND SETOUT ISSUED'
        )
    ) AS writs_issued,

    -- Setouts processed on this day
    COUNT(*) FILTER (
        WHERE d.text IN (
            'SET OUT ISSUED',
            'WRIT OF RESTITUTION AND SETOUT ISSUED'
        )
    ) AS setouts_processed,

    -- Setouts completed on this day
    COUNT(*) FILTER (
        WHERE d.text IN (
            'WRIT OF RESTITUTION RETURNED SHOWING CONTENTS TRASH/SET OUT COMPLETE',
            'WRIT OF RESTITUTION RETURNED SHOWING SET OUT COMPLETED'
        )
    ) AS setouts_completed

FROM latest_snapshot s
JOIN cases_docketentry d
    ON d.snapshot_id = s.id

GROUP BY d.date
ORDER BY d.date;
"""

DROP_SQL = "DROP VIEW daily_events;"

class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_alter_disposition_status_date"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
