# Generated by Django 6.0.3 on 2026-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('CVG', 'Forcible Entry and Detainer'), ('CVF', 'Contract'), ('CVR', 'Rent Escrow'), ('CVE', 'Personal Injury')])),
                ('case_number', models.IntegerField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.BinaryField(null=True)),
                ('return_code', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'category', 'case_number', 'scraped_at')},
            },
        ),
    ]
