# Generated by Django 6.0.3 on 2026-04-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcmcclerk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="case_number",
            new_name="number",
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("year", "category", "number", "scraped_at")},
        ),
    ]
