# Generated by Django 6.0.3 on 2026-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcmcclerk", "0002_rename_case_number_page_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField()),
                ("hash", models.CharField()),
            ],
        ),
    ]
