# Generated by Django 6.0.3 on 2026-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcmcclerk", "0003_caseoverview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseOverview",
        ),
        migrations.AddField(
            model_name="page",
            name="overview_digest",
            field=models.CharField(null=True),
        ),
    ]
