# Generated by Django 6.0.3 on 2026-05-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_disposition_options_alter_event_options"),
        ("fcmcclerk", "0004_delete_caseoverview_page_overview_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.casesnapshot",
            ),
        ),
    ]
