# Generated by Django 6.0.3 on 2026-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcmcclerk", "0005_page_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="filed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="status",
            field=models.CharField(blank=True, null=True),
        ),
    ]
