# Generated by Django 6.0.3 on 2026-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcmcclerk", "0006_page_filed_page_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.CharField(),
        ),
    ]
