# Generated by Django 6.0.3 on 2026-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("category", models.CharField()),
                ("number", models.IntegerField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(null=True)),
                ("return_code", models.IntegerField()),
            ],
            options={
                "unique_together": {("year", "category", "number", "scraped_at")},
            },
        ),
    ]
