# Generated by Django 6.0.3 on 2026-07-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tmcclerk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_start", models.DateField()),
                ("content", models.CharField(null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("return_code", models.IntegerField()),
            ],
        ),
    ]
