# Generated by Django 6.0.3 on 2026-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinsheet",
            name="file_hash",
            field=models.CharField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
