# Generated by Django 6.0.3 on 2026-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0002_checkinsheet_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinsheet",
            name="llm_numbers",
            field=models.JSONField(null=True),
        ),
    ]
