# Generated by Django 6.0.3 on 2026-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0003_checkinsheet_llm_numbers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkinsheet",
            old_name="llm_numbers",
            new_name="processed",
        ),
        migrations.AddField(
            model_name="checkinsheet",
            name="possible_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinsheet",
            name="possible_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinsheet",
            name="validated",
            field=models.BooleanField(default=False),
        ),
    ]
