# Generated by Django 6.0.3 on 2026-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0004_rename_llm_numbers_checkinsheet_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinsheet",
            name="processed",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
