# Generated by Django 6.0.3 on 2026-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0005_alter_checkinsheet_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinsheet",
            name="event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
