# Generated by Django 6.0.3 on 2026-07-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0006_checkinsheet_event_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocketSessionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_start",
                    models.DateTimeField(
                        help_text="ISO Start Timestamp of the Session Window",
                        unique=True,
                    ),
                ),
                (
                    "check_in_store",
                    models.JSONField(
                        blank=True, default=dict, help_text="Map of party.id -> boolean"
                    ),
                ),
                (
                    "attorney_check_store",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of attorneyName -> boolean",
                    ),
                ),
                (
                    "case_notes_store",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of item.id -> freetext note string",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
