# Generated by Django 6.0.3 on 2026-07-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attending", "0007_docketsessionstate"),
        ("cases", "0011_latestoverview"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresenceCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_number", models.CharField()),
                ("note", models.CharField()),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.courtcase",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attending.checkinsheet",
                    ),
                ),
            ],
        ),
    ]
