# Generated by Django 6.0.3 on 2026-05-29 20:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_address", models.CharField()),
                ("street_number", models.CharField(blank=True)),
                ("street_name", models.CharField(blank=True)),
                ("street_type", models.CharField(blank=True)),
                ("street_direction", models.CharField(blank=True)),
                ("unit_type", models.CharField(blank=True)),
                ("unit_number", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                ("county", models.CharField(blank=True)),
                ("state", models.CharField(blank=True)),
                ("state_code", models.CharField(blank=True)),
                ("postal_code", models.CharField(blank=True)),
                ("postal_code_ext", models.CharField(blank=True)),
                ("country", models.CharField(blank=True)),
                ("rooftop", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("geocode_score", models.FloatField(blank=True, null=True)),
                ("geocode_rank", models.FloatField(blank=True, null=True)),
                ("geocode_type", models.CharField(blank=True)),
                ("raw_geocode", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
