# Generated by Django 6.0.3 on 2026-05-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0005_auto_20260508_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanDocketEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("text", models.CharField()),
                ("scan", models.FileField(null=True, upload_to="nextgen")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.courtcase",
                    ),
                ),
            ],
        ),
    ]
