# Generated by Django 6.0.3 on 2026-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextgen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scandocketentry",
            name="filename",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
