# Generated by Django 6.0.3 on 2026-05-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20260508_1553"),
        ("nextgen", "0002_scandocketentry_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(null=True)),
                ("return_code", models.IntegerField()),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.courtcase",
                    ),
                ),
            ],
        ),
    ]
