# Generated by Django 6.0.3 on 2026-06-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextgen", "0003_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagdecAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("page_number", models.IntegerField()),
                ("good_matches", models.IntegerField()),
                ("diff_sum", models.BigIntegerField()),
                ("m11", models.FloatField()),
                ("m12", models.FloatField()),
                ("m13", models.FloatField()),
                ("m21", models.FloatField()),
                ("m22", models.FloatField()),
                ("m23", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="scandocketentry",
            name="magdec_analyses",
            field=models.ManyToManyField(to="nextgen.magdecanalysis"),
        ),
        migrations.CreateModel(
            name="RoiCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roi_id", models.IntegerField()),
                ("color_hex", models.CharField(max_length=7)),
                ("count_nonwhite", models.IntegerField()),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roi_counts",
                        to="nextgen.magdecanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["roi_id"],
            },
        ),
    ]
