# Generated by Django 6.0.3 on 2026-06-02 17:30

from django.db import migrations

CREATE_SQL = """
CREATE VIEW nextgen_magistrate_presence AS
WITH ranked AS (
    SELECT
        result_id,
        roi_id,
        count_nonwhite,
        ROW_NUMBER() OVER (
            PARTITION BY result_id
            ORDER BY count_nonwhite DESC
        ) AS rn
    FROM nextgen_roicount
),
analysis_summary AS (
    SELECT
        a.id AS analysis_id,
        a.*,                                                             
                                                                        
        MAX(CASE WHEN roi_id = 0 THEN count_nonwhite END) AS check_0_dismissed,
        MAX(CASE WHEN roi_id = 1 THEN count_nonwhite END) AS check_1_reassign,
        MAX(CASE WHEN roi_id = 2 THEN count_nonwhite END) AS check_2_only_defendant,
        MAX(CASE WHEN roi_id = 3 THEN count_nonwhite END) AS check_3_none,
        MAX(CASE WHEN roi_id = 4 THEN count_nonwhite END) AS check_4_both,
        MAX(CASE WHEN roi_id = 5 THEN count_nonwhite END) AS check_5_only_plaintiff,
                                                               
        MAX(CASE WHEN rn = 1 THEN roi_id END) AS top_roi_id,
        MAX(CASE WHEN rn = 1 THEN count_nonwhite END) AS top_count,
        MAX(CASE WHEN rn = 2 THEN count_nonwhite END) AS second_count,
                                                                        
        COALESCE(
            CAST(MAX(CASE WHEN rn = 1 THEN count_nonwhite END) AS FLOAT)
            / NULLIF(MAX(CASE WHEN rn = 2 THEN count_nonwhite END), 0),
            99999
        ) AS top_to_second_ratio

    FROM ranked r
    JOIN nextgen_magdecanalysis a
      ON a.id = r.result_id
    GROUP BY a.id
)

SELECT
    s.*,
    sde.id AS entry_id,
    sde.date,
    sde.text,
    sde.scan,
    sde.case_id,
    sde.filename,
    cc.source_id,
    cc.case_number
FROM analysis_summary s
JOIN nextgen_scandocketentry_magdec_analyses link
  ON link.magdecanalysis_id = s.analysis_id
JOIN nextgen_scandocketentry sde
  ON sde.id = link.scandocketentry_id
JOIN cases_courtcase cc
  ON cc.id = sde.case_id;

"""

DROP_SQL = "DROP VIEW nextgen_magistrate_presence;"


class Migration(migrations.Migration):

    dependencies = [
        ("nextgen", "0004_magdecanalysis_scandocketentry_magdec_analyses_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        )
    ]
