# Generated by Django 6.0.3 on 2026-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("record_number", models.CharField()),
                ("record_type", models.CharField()),
                ("address", models.CharField()),
                ("description", models.CharField()),
                ("status", models.CharField()),
                ("scraped_at", models.DateTimeField()),
            ],
        ),
    ]
