# Generated by Django 6.0.3 on 2026-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeviolation",
            name="scraped_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
