# Generated by Django 6.0.3 on 2026-07-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geocode", "0001_initial"),
        ("violations", "0002_alter_codeviolation_scraped_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeviolation",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geocode.location",
            ),
        ),
    ]
